lesson:
  number: 2
  title: "Функции в JavaScript"
  topic: "Создание и вызов функций, работа с параметрами и возвращаемыми значениями"
  duration: 90

key_concepts:
  - "Создание функций, ключевое слово function, стрелочные функции"
  - "Упоминание нескольких других способов создания функций"
  - "Вызов функций напрямую и через call и apply, разница между ними"
  - "Сохранение контекста при вызове функции, bind, почему в стрелочных функциях контекст не меняется в момент вызова"
  - "Детальный разбор синтаксиса объявления функций"
  - "Деструктуризация объектов и массивов в параметрах функций, неопределенное количество аргументов"

fun_facts:
  - "Свойства length и name у функций"
  - "Объявленные по умолчанию arguments и event"

learning_objectives:
  - "Уметь объявлять именованные и анонимные функции"
  - "Уметь передавать параметры в функцию и получать возвращаемое значение"
  - "Уметь передавать в функцию указанных контекст"

practice_exercises:
  - "Создать функцию, которая принимает два числа и возвращает их сумму"
  - "Создать функцию, которая принимает имя человека и его возраст и выводит в консоль две строки. В первой `Имя: ${name}`, во второй"
  - "Создать функцию, которая принимает три числа и возвращает самое маленькое из них"
  - "Создать стрелочную функцию с именем `sum`"
  - "Создать анонимную нестрелочную функцию"
  - "Создать функцию, которая принимает две функции и возвращает функцию, которая вызывает первую и затем вторую функцию, передав в первую свой аргумент, а во вторую - результат выполнения первой. В итоге эта функция должна вернуть результат выполнения второй функции"
  - "Создать функцию, принимающую объект и возвращающую значение свойства `name`"
