lesson:
  number: 1
  title: "Типы данных в JavaScript"
  topic: "Основные типы данных, с которыми мы будем работать"
  duration: 90

key_concepts:
  - "Ключевые слова для обьявления переменных"
  - "var, как наследие обратной совместимости, отличие в поведении"
  - "Строки, числа, логические значения"

fun_facts:
  - "Ошибка 0.1 + 0.2, которая ошибкой не является"
  - "Внезапно, деление на ноль"
  - "Число, которое не равняется себе"

learning_objectives:
  - "Уметь объявлять переменные и назначать им значения"
  - "Уметь работать с числовыми значениями и выполнять над ними арифметические операции"
  - "Уметь использовать операторы сравнения и логические операторы"

practice_exercises:
  - "Задача 1: Объявление переменных"
    description: "Объявите переменную `name` и присвойте ей значение 'Василий'."
    code: |
      let name = 'Василий';
    solution: |
      let name = 'Василий';
    tests:
      - "name === 'Василий'"
  - "Задача 2: Сложение чисел"
    description: "Сложите числа 5 и 3 и присвойте результат переменной `result`."
    code: |
      let result = 5 + 3;
    solution: |
      let result = 5 + 3;
    tests:
      - "result === 8"
  - "Задача 3: Сравнение строк"
    description: "Сравните строки 'apple' и 'banana' и присвойте результат переменной `comparison`."
    code: |
      let comparison = 'apple' === 'banana';
    solution: |
      let comparison = 'apple' === 'banana';
    tests:
      - "comparison === false"
