lesson:
  number: 1
  title: "Типы данных в JavaScript"
  topic: "Основные типы данных, с которыми мы будем работать"
  duration: 90
  type: "theory"

key_concepts:
  - "Ключевые слова для обьявления переменных"
  - "var, как наследие обратной совместимости, отличие в поведении"
  - "Строки, числа, логические значения"

fun_facts:
  - "Ошибка 0.1 + 0.2, которая ошибкой не является"
  - "Внезапно, деление на ноль"
  - "Число, которое не равняется себе"

learning_objectives:
  - "Уметь объявлять переменные и назначать им значения"
  - "Уметь работать с числовыми значениями и выполнять над ними арифметические операции"
  - "Уметь использовать операторы сравнения и логические операторы"

practice_exercises:
  - name: "Объявление переменных"
    description: "Объявите переменную `name` и присвойте ей значение 'Василий'."
  - name: "Сложение чисел"
    description: "Сложите числа 5 и 3 и присвойте результат переменной `result`."
  - name: "Сравнение строк"
    description: "Сравните строки 'apple' и 'banana' и присвойте результат переменной `comparison`."
