lesson:
  number: 7
  title: "Модификация списка"
  topic: "Модификация списка, удаление элементов, форма для добавления слов"
  duration: 90
  type: "practice"

expected_results:
  - "Требования из урока 5 продолжают соблюдаться"
  - "Пользователь может удалить слово из списка"
  - "Пользователь может добавить слово в список"

project:
  name: "crossword"
  description: "Редактирование и заполнение кроссворда"
  steps:
    - name: "Добавляем методы removeWord(word) и updateWord(word, description) в WordList"
    - name: "Дополняем функцию renderWord() таким образом, чтобы третьей ячейкой отображалась кнопка для удаления"
    - name: "Добавляем обработчик события click на список слов (с проверкой event.target) для удаления слова, с вызовом метода removeWord()"
    - name: "Добавляем в index.html форму для добавления слов"
    - name: "Добавляем обработчик события click в форме добавления на кнопку добавления слова с использованием метода addWord()"
    - name: ""
