lesson:
  number: 7
  title: "Модификация списка"
  topic: "Модификация списка, удаление элементов, форма для добавления слов"
  duration: 90
  type: "practice"

expected_results:
  - "Требования из урока 6 продолжают соблюдаться"
  - "Пользователь может удалить слово из списка"
  - "Пользователь может добавить слово в список"

project:
  name: "crossword"
  description: "Редактирование и заполнение кроссворда"
  steps:
    - name: "Добавляем методы removeWord(word) и updateWord(word, description) в WordList"
      path: "src/step01"
      actions:
        - name: "Добавляем методы в WordList"
          ref:
            - "word-list.js@remove-word"
            - "word-list.js@update-word"
      expected:
        - "Вызов wordList.removeWord(word) должен удалять слова с указанным значением поля word"
        - "Вызов wordList.updateWord(word, description) должен обновлять указанное слово"

    - name: "Дополняем функцию renderWord() таким образом, чтобы третьей ячейкой отображалась кнопка для удаления"
      path: "src/step02"
      actions:
        - name: "Меняем шаблон для вывода строки, соответствующей слову"
          ref:
            - "renderers.js@word-template"
      expected:
        - "В каждой строке таблицы должна быть кнопка с крестиком"

    - name: "Добавляем обработчик события click на список слов (с проверкой event.target) для удаления слова, с вызовом метода removeWord()"
      path: "src/step03"
      actions:
        - name: "Добавляем обработчик события click на контейнер списка слов"
          ref:
            - name: "Создаем файл handlers.js"
              ref: "handlers.js"
            - name: "Создаем функцию attachHandlers и экспортируем ее из handlers.js"
              ref: "handlers.js@declare"
            - name: "Описываем обработчик для кнопок удаления"
              ref: "handlers.js@remove-button"
            - name: "Импортируем attachHandlers в main.js и скармливаем ему #word-list"
              ref: ["main.js@import", "main.js@attach"]
      expected:
        - "Обработчик должен быть назначен не на каждый крестик, а на весь список, идеально - на контейнер #word-list"
        - "При клике на кнопку удаления слово должно удаляться из списка"

    - name: "Добавляем в index.html форму для добавления слов"
    - name: "Добавляем обработчик события click в форме добавления на кнопку добавления слова с использованием метода addWord()"
    - name: "Меняем поведение по событию click в списке слов, чтобы при клике на tr сохранялось слово, которое нужно обновить"
    - name: "Меняем обработчик события click в форме добавления слова так, чтобы если было выбрано слово, слово бы обновлялось"
    - name: "Дополняем обработчики, меняющие список слов вызовом колбэка, который будем передавать при создании списка, чтобы рендерить список при изменениях"
