lesson:
  number: 3
  title: "Объекты в JavaScript"
  topic: "Создание объектов, модификация свойств, вызов методов"
  duration: 90
  type: "theory"

key_concepts:
  - "Создание объектов, как литералов, вызов методов (если они добавлены), контекст вызова"
  - "Создание объектов через new ObjConstructor(), свойство __proto__, наследование, в том числе на несколько уровней"
  - "Object.create(prototype)"
  - "Классы, ключевые слова class и extends, метод constructor, наследование"
  - "Свойства объектов, вызывающие методы при чтении и модификации (getters и setters)"

fun_facts:
  - "null это тоже объект"
  - "Как правило, прототипирование в JavaScript дает выигрыш в производительности после того, как объектов стало заметно больше 10000, поэтому всегда думайте, насколько большим будет ваш проект"

learning_objectives:
  - "Уметь объявлять объекты, как литералы"

code_examples:
  - "Пример создания объекта как литерала"
  - "Пример создания объекта через new ObjConstructor()"
  - "Пример использования Object.create(prototype)"
  - "Пример использования классов и наследования"
  - "Пример объекта с геттерами, которые будут вызваны только в момент чтения"

practice_exercises:
  - "Создать пустой объект"
  - "Создать объект с методом, который будет возвращать свойство объекта, например, метод getName()"
  - "Создаем класс Point, у которого есть два поля x и y"
  - "Добавляем в класс Point метод move(newX, newY)"
  - "Добавляем в класс Point метод moveBy(shiftX, shiftY)"
  - "Добавляем в класс Point метод mirror(zeroX, zeroY)"
