lesson:
  number: 4
  title: "Массивы и работа с ними в JavaScript"
  topic: "Массивы, создание, методы"
  duration: 90

key_concepts:
  - "Использование forEach, map, filter, reduce"
  - "Модификация массивов с помощью методов push, pop, shift, unshift"
  - "Сортировка массивов с помощью метода sort"
  - "Поиск элементов в массиве с помощью методов indexOf, lastIndexOf, find, findIndex"

fun_facts:
  - "Object.keys([1, 2, 3]) возвращает массив ['0', '1', '2'], который содержит индексы элементов массива, как строковые значения."
  - "Метод sort() изменяет исходный массив и возвращает отсортированный массив. При этом уже какое-то время существует метод toSorted(), который не меняет исходный массив и возвращает новый отсортированный массив."

learning_objectives:
  - "Уметь объявлять массивы, как литералы"

code_examples:
  - "Пример создания объекта как литерала"
  - "Пример создания объекта через new ObjConstructor()"
  - "Пример использования Object.create(prototype)"
  - "Пример использования классов и наследования"
  - "Пример объекта с геттерами, которые будут вызваны только в момент чтения"

practice_exercises:
  - "Создать пустой объект"
  - "Создать объект с методом, который будет возвращать свойство объекта, например, метод getName()"
  - "Создаем класс Point, у которого есть два поля x и y"
  - "Добавляем в класс Point метод move(newX, newY)"
  - "Добавляем в класс Point метод moveBy(shiftX, shiftY)"
  - "Добавляем в класс Point метод mirror(zeroX, zeroY)"
