lesson:
  number: 4
  title: "Массивы и работа с ними в JavaScript"
  topic: "Массивы, создание, методы"
  duration: 90
  type: "theory"

key_concepts:
  - "Использование forEach, map, filter, reduce"
  - "Модификация массивов с помощью методов push, pop, shift, unshift"
  - "Сортировка массивов с помощью метода sort"
  - "Поиск элементов в массиве с помощью методов indexOf, lastIndexOf, find, findIndex"
  - "Уметь получить необходимую часть массива с помощью методов slice"

fun_facts:
  - "Object.keys([1, 2, 3]) возвращает массив ['0', '1', '2'], который содержит индексы элементов массива, как строковые значения."
  - "Метод sort() изменяет исходный массив и возвращает отсортированный массив. При этом уже какое-то время существует метод toSorted(), который не меняет исходный массив и возвращает новый отсортированный массив."

learning_objectives:
  - "Уметь объявлять массивы, как литералы"
  - "Уметь выбирать нужную часть массива с помощью методов slice"
  - "Уметь выбирать из массива элементы по условию при помощи filter"
  - "Уметь преобразовывать массивы с помощью методов map, reduce"
  - "Уметь выполнять действие для элементов массива с помощью forEach"
  - "Иметь представление о трех аргументах методов forEach, filter, map"

code_examples:
  - "Пример создания массива как литерала"
  - "Получение массива слов из строки, разделенной прообелами"
  - "Получение длины массива"
  - "Суммирование цифр числа с преобразованием в строку, затем в массив и так далее"

practice_exercises:
  - "Создать пустой массив"
  - "Создать массив 7 дней недели"
  - "Выбрать только выходные дни недели"
  - "Выбрать только рабочие дни недели"
  - "Для массива от 1 до 10 получить массив квадратов чисел"
  - "Для массива от 1 до 10 получить сумму элементов"
